config:
    send_anonymous_usage_stats: False
    use_colors: True
    partial_parse: True

mybi_dbt_ramm:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    prod:
      type: clickhouse
      schema: "{{ env_var('DBT_SCHEMA') }}"
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT') | int }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      secure: "{{ env_var('DBT_SECURE') | as_bool }}"
      threads: 3  
    # ci:
    #   type: clickhouse
    #   schema: "{{ env_var('DBT_SCHEMA') }}"
    #   host: "{{ env_var('DBT_HOST') }}"
    #   port: "{{ env_var('DBT_PORT') | int }}"
    #   user: "{{ env_var('DBT_USER') }}"
    #   password: "{{ env_var('DBT_PASSWORD') }}"
    #   secure: "{{ env_var('DBT_SECURE') | as_bool }}"
    #   threads: 3  
